### ISSUE TITLE
Gumroad Import still failing.

### ISSUE THREAD

**Issue by calvinthefreak** [OpenYiff/Kitsune#12]
I tried to Import something from gumroad, mainly .zip and multiple images.
My local instance throws following at me:
```log
DEBUG:server:[bac10734]: Starting import. Your import id is bac10734.
DEBUG:server:[bac10734]: Starting import: ZYX from user XYZ
DEBUG:PIL.PngImagePlugin:STREAM b'IHDR' 16 13
DEBUG:PIL.PngImagePlugin:STREAM b'IDAT' 41 2654354
ERROR:server:[bac10734]: Internal error. Contact site staff on Telegram.
Traceback (most recent call last):
  File "./src/lib/import_manager.py", line 5, in import_posts
    target(import_id, *args)
  File "./src/importers/gumroad.py", line 119, in import_posts
    'https://gumroad.com' + download_data['download_info'][_file['id']]['download_url'],
KeyError: 'download_info'
```

Cookie was freshly taken from gumroad.
I don't know, why it wont work.

Some site-notes:
I use the newest docker version deployed 4 Hours ago.
I am running on an Debian Based machine (Proxmox to be precise).

**Comment by kemono-bugs** [comment]
[Fixed.](https://github.com/OpenYiff/Kitsune/commit/317aa6efcdf711d02ea9b0b52e999538cdba2f8b)
