### ISSUE TITLE
Discord importer

### ISSUE THREAD

**Issue by kemono-bugs** [OpenYiff/Kitsune#2]
The Discord importer needs to be reimplemented.

**Comment by kemono-bugs** [comment]
There's a bounty on this now.
https://www.bountysource.com/issues/98580361-discord-importer

**Comment by aj4ayushjain** [comment]
I am interested in working on this. any readme docs / guides to get started quickly.

**Comment by kemono-bugs** [comment]
There's the old Node.js implementation that you can use for reference; https://github.com/OpenYiff/Kemono/blob/master/importers/discord.js
Also Discord's official documentation; https://discord.com/developers/docs/intro

**Comment by WafflesK** [comment]
Implemented in PR #10

**Comment by kemono-bugs** [comment]
Merged, thank you @WafflesK!
